import type { VariableKey } from "@/lib/climate";
export type StoryText={en:string;bn:string};
export type StoryArtwork="earth"|"delta"|"signals"|"evidence"|"future";
export type StorySound="space"|"river"|"forest"|"city"|"rain"|"signal"|"dawn";
export type StoryScene={id:string;chapter:number;chapterTitle:StoryText;title:StoryText;speaker:StoryText;dialogue:StoryText;narration:StoryText;artwork:StoryArtwork;sound:StorySound;evidence?:{districtId:string;variable:VariableKey}};
const C:Record<1|2|3|4|5,StoryText>={1:{en:"The signal",bn:"সংকেত"},2:{en:"The living delta",bn:"জীবন্ত বদ্বীপ"},3:{en:"Five clues",bn:"পাঁচটি সূত্র"},4:{en:"How evidence speaks",bn:"প্রমাণ যেভাবে কথা বলে"},5:{en:"Our next page",bn:"আমাদের পরের পৃষ্ঠা"}};
export const KIDS_STORY:[StoryScene,...StoryScene[]]=[
{id:"night",chapter:1,chapterTitle:C[1],artwork:"earth",sound:"space",title:{en:"A light over Bangladesh",bn:"বাংলাদেশের আকাশে এক আলো"},speaker:{en:"Tara",bn:"তারা"},dialogue:{en:"Rafi, look! That little satellite is trying to tell us something.",bn:"রাফি, দেখো! ছোট্ট স্যাটেলাইটটা যেন আমাদের কিছু বলতে চাইছে।"},narration:{en:"On a clear night, Tara and Rafi meet a tiny visitor named Neel. Neel watches Earth from space, but never guesses what is happening below.",bn:"এক পরিষ্কার রাতে তারা আর রাফি নীল নামের এক ছোট্ট অতিথির দেখা পায়। নীল মহাকাশ থেকে পৃথিবী দেখে, কিন্তু নিচে কী ঘটছে তা কখনো অনুমান করে না।"}},
{id:"guide",chapter:1,chapterTitle:C[1],artwork:"earth",sound:"signal",title:{en:"The evidence guide",bn:"প্রমাণের গাইড"},speaker:{en:"Neel",bn:"নীল"},dialogue:{en:"I carry observations. You bring questions. Together, we can read the story of change.",bn:"আমি পর্যবেক্ষণ নিয়ে এসেছি। তোমরা প্রশ্ন আনো। একসঙ্গে আমরা পরিবর্তনের গল্প পড়ব।"},narration:{en:"The TerraBangla guide opens a path from the whole Earth to Bangladesh. Every number on the journey must come from a cached NASA record.",bn:"টেরাবাংলার গাইড পুরো পৃথিবী থেকে বাংলাদেশের পথে একটি দরজা খুলে দেয়। এই যাত্রার প্রতিটি সংখ্যা আসবে সংরক্ষিত নাসা রেকর্ড থেকে।"}},
{id:"delta",chapter:2,chapterTitle:C[2],artwork:"delta",sound:"river",title:{en:"A country shaped by water",bn:"জলের আঁকা একটি দেশ"},speaker:{en:"Rafi",bn:"রাফি"},dialogue:{en:"The rivers connect fields, forests, towns and the sea—like one enormous living system.",bn:"নদীগুলো মাঠ, বন, শহর আর সাগরকে জুড়ে দিয়েছে—যেন এক বিশাল জীবন্ত ব্যবস্থা।"},narration:{en:"They fly over the delta. Bangladesh has 64 districts, and TerraBangla keeps a separate evidence record for every one of them.",bn:"তারা বদ্বীপের ওপর দিয়ে উড়ে যায়। বাংলাদেশের ৬৪টি জেলা, আর টেরাবাংলা প্রতিটি জেলার জন্য আলাদা প্রমাণের রেকর্ড রাখে।"}},
{id:"signals",chapter:2,chapterTitle:C[2],artwork:"delta",sound:"signal",title:{en:"Five ways to observe",bn:"পর্যবেক্ষণের পাঁচটি পথ"},speaker:{en:"Evidence guide",bn:"প্রমাণের গাইড"},dialogue:{en:"We will follow vegetation, land temperature, air temperature, sunlight and rainfall.",bn:"আমরা উদ্ভিদ, ভূপৃষ্ঠের তাপমাত্রা, বায়ুর তাপমাত্রা, সূর্যালোক ও বৃষ্টিপাত অনুসরণ করব।"},narration:{en:"Each signal answers a different question. None can tell the whole climate story alone.",bn:"প্রতিটি সংকেত আলাদা প্রশ্নের উত্তর দেয়। একটিমাত্র সংকেত কখনো পুরো জলবায়ুর গল্প বলে না।"}},
{id:"green",chapter:3,chapterTitle:C[3],artwork:"signals",sound:"forest",title:{en:"Clue one: greenness",bn:"প্রথম সূত্র: সবুজের পরিমাণ"},speaker:{en:"Tara",bn:"তারা"},dialogue:{en:"NDVI helps us compare plant greenness. It is a signal—not a photograph of every leaf.",bn:"NDVI উদ্ভিদের সবুজের পরিমাণ তুলনা করতে সাহায্য করে। এটি একটি সংকেত—প্রতিটি পাতার ছবি নয়।"},narration:{en:"At Satkhira, they open the full annual vegetation record. They do not decide from only the first and last year.",bn:"সাতক্ষীরায় তারা পুরো বার্ষিক উদ্ভিদ রেকর্ড খুলে দেখে। শুধু প্রথম ও শেষ বছর দেখে সিদ্ধান্ত নেয় না।"},evidence:{districtId:"satkhira",variable:"ndvi"}},
{id:"land",chapter:3,chapterTitle:C[3],artwork:"signals",sound:"city",title:{en:"Clue two: the land",bn:"দ্বিতীয় সূত্র: ভূপৃষ্ঠ"},speaker:{en:"Rafi",bn:"রাফি"},dialogue:{en:"Ground and rooftops can feel different from the air. Land temperature has its own record.",bn:"মাটি ও ছাদের তাপ বাতাসের চেয়ে আলাদা হতে পারে। তাই ভূপৃষ্ঠের তাপমাত্রার আলাদা রেকর্ড আছে।"},narration:{en:"Rajshahi's land-temperature observations come from MODIS. The trend test checks the complete sequence of years.",bn:"রাজশাহীর ভূপৃষ্ঠের তাপমাত্রার পর্যবেক্ষণ MODIS থেকে আসে। প্রবণতা পরীক্ষা সব বছরের ধারাবাহিকতা যাচাই করে।"},evidence:{districtId:"rajshahi",variable:"lst"}},
{id:"air",chapter:3,chapterTitle:C[3],artwork:"signals",sound:"city",title:{en:"Clue three: the air",bn:"তৃতীয় সূত্র: বাতাস"},speaker:{en:"Neel",bn:"নীল"},dialogue:{en:"Air temperature is measured separately. Similar names do not mean identical evidence.",bn:"বায়ুর তাপমাত্রা আলাদাভাবে মাপা হয়। নাম কাছাকাছি হলেও প্রমাণ এক নয়।"},narration:{en:"For Dhaka, NASA POWER provides a long annual record. TerraBangla calculates statistics locally from cached observations.",bn:"ঢাকার জন্য NASA POWER দীর্ঘ বার্ষিক রেকর্ড দেয়। টেরাবাংলা সংরক্ষিত পর্যবেক্ষণ থেকে স্থানীয়ভাবে পরিসংখ্যান হিসাব করে।"},evidence:{districtId:"dhaka",variable:"temperature"}},
{id:"sun",chapter:3,chapterTitle:C[3],artwork:"signals",sound:"signal",title:{en:"Clue four: sunlight",bn:"চতুর্থ সূত্র: সূর্যালোক"},speaker:{en:"Tara",bn:"তারা"},dialogue:{en:"Sunlight powers Earth's systems and solar panels, but its amount changes from year to year.",bn:"সূর্যালোক পৃথিবীর ব্যবস্থা আর সোলার প্যানেল চালায়, তবে এর পরিমাণ বছরভেদে বদলায়।"},narration:{en:"In Khulna, the team compares annual solar radiation without treating one cloudy year as a long-term trend.",bn:"খুলনায় দলটি বার্ষিক সৌর বিকিরণ তুলনা করে; একটি মেঘলা বছরকে দীর্ঘমেয়াদি প্রবণতা ধরে না।"},evidence:{districtId:"khulna",variable:"solar"}},
{id:"rain",chapter:3,chapterTitle:C[3],artwork:"signals",sound:"rain",title:{en:"Clue five: rainfall",bn:"পঞ্চম সূত্র: বৃষ্টিপাত"},speaker:{en:"Rafi",bn:"রাফি"},dialogue:{en:"Heavy rain today is weather. A pattern across many years is the evidence we test for climate.",bn:"আজকের ভারী বৃষ্টি হলো আবহাওয়া। বহু বছরের ধরনই হলো জলবায়ুর জন্য পরীক্ষিত প্রমাণ।"},narration:{en:"Sylhet's annual rainfall record rises and falls. The children test the whole pattern before describing a direction.",bn:"সিলেটের বার্ষিক বৃষ্টিপাত কখনো বাড়ে, কখনো কমে। দিক বলার আগে শিশুরা পুরো ধরনটি পরীক্ষা করে।"},evidence:{districtId:"sylhet",variable:"precipitation"}},
{id:"dots",chapter:4,chapterTitle:C[4],artwork:"evidence",sound:"signal",title:{en:"Two dots are not a trend",bn:"দুটি বিন্দু প্রবণতা নয়"},speaker:{en:"Evidence guide",bn:"প্রমাণের গাইড"},dialogue:{en:"Early and recent values are clues, but every year between them also matters.",bn:"আগের ও সাম্প্রতিক মান সূত্র, কিন্তু মাঝের প্রতিটি বছরও গুরুত্বপূর্ণ।"},narration:{en:"A line between two endpoints can fool us. TerraBangla uses every annual observation available in the selected period.",bn:"দুটি শেষবিন্দুর মাঝের রেখা আমাদের ভুল বোঝাতে পারে। টেরাবাংলা নির্বাচিত সময়ের প্রতিটি বার্ষিক পর্যবেক্ষণ ব্যবহার করে।"}},
{id:"test",chapter:4,chapterTitle:C[4],artwork:"evidence",sound:"space",title:{en:"Test the direction",bn:"দিক যাচাই করো"},speaker:{en:"Neel",bn:"নীল"},dialogue:{en:"Mann–Kendall checks direction. The p-value helps us decide whether the pattern is clear.",bn:"Mann–Kendall দিক যাচাই করে। p-value আমাদের বুঝতে সাহায্য করে ধরনটি স্পষ্ট কি না।"},narration:{en:"If the evidence is not statistically significant, the honest conclusion is no clear change—even when two endpoints differ.",bn:"প্রমাণ পরিসংখ্যানগতভাবে তাৎপর্যপূর্ণ না হলে সৎ সিদ্ধান্ত হলো—স্পষ্ট পরিবর্তন নেই; এমনকি দুই শেষবিন্দু আলাদা হলেও।"}},
{id:"rate",chapter:4,chapterTitle:C[4],artwork:"evidence",sound:"signal",title:{en:"Measure the rate",bn:"পরিবর্তনের হার মাপো"},speaker:{en:"Tara",bn:"তারা"},dialogue:{en:"Theil–Sen estimates the rate while resisting the pull of unusual years.",bn:"Theil–Sen অস্বাভাবিক বছরের টান সামলে পরিবর্তনের হার হিসাব করে।"},narration:{en:"Direction, rate and uncertainty belong together. TerraBangla never lets an illustration or AI invent these numbers.",bn:"দিক, হার ও অনিশ্চয়তা একসঙ্গে দেখা দরকার। টেরাবাংলায় কোনো ছবি বা এআই এই সংখ্যাগুলো বানায় না।"}},
{id:"journal",chapter:5,chapterTitle:C[5],artwork:"future",sound:"dawn",title:{en:"The evidence journal",bn:"প্রমাণের খাতা"},speaker:{en:"Rafi",bn:"রাফি"},dialogue:{en:"Now we can ask better questions: Which place? Which signal? Which years? Which source?",bn:"এখন আমরা ভালো প্রশ্ন করতে পারি: কোন স্থান? কোন সংকেত? কোন বছর? কোন উৎস?"},narration:{en:"At sunrise, the team writes a new rule: observe carefully, test the full record, name uncertainty and always show the source.",bn:"সূর্যোদয়ে দলটি একটি নতুন নিয়ম লেখে: মন দিয়ে পর্যবেক্ষণ করো, পুরো রেকর্ড পরীক্ষা করো, অনিশ্চয়তা বলো এবং সবসময় উৎস দেখাও।"}},
{id:"challenge",chapter:5,chapterTitle:C[5],artwork:"future",sound:"dawn",title:{en:"Your turn to read the evidence",bn:"এবার প্রমাণ পড়ার পালা তোমার"},speaker:{en:"Evidence guide",bn:"প্রমাণের গাইড"},dialogue:{en:"The story is complete. The final review asks only about clues you met on this journey.",bn:"গল্প শেষ। শেষের পর্যালোচনায় শুধু এই যাত্রায় দেখা সূত্রগুলো নিয়েই প্রশ্ন থাকবে।"},narration:{en:"Tara, Rafi and Neel return the evidence journal to you. Climate understanding begins with a good question, a complete record and an honest answer.",bn:"তারা, রাফি আর নীল প্রমাণের খাতাটি তোমার হাতে দেয়। জলবায়ু বোঝা শুরু হয় ভালো প্রশ্ন, পূর্ণ রেকর্ড আর সৎ উত্তর দিয়ে।"}}
];
