import type { VariableKey } from '@/lib/climate';
export type StoryText={en:string;bn:string};
export type StoryArtwork='earth'|'delta'|'signals'|'evidence'|'future';
export type StorySound='space'|'river'|'forest'|'city'|'rain'|'signal'|'dawn';
export type StoryScene={id:string;chapter:number;chapterTitle:StoryText;title:StoryText;speaker:StoryText;dialogue:StoryText;narration:StoryText;artwork:StoryArtwork;sound:StorySound;evidence?:{districtId:string;variable:VariableKey}};
const C:Record<number,StoryText>={1:{en:'One shared Earth',bn:'আমাদের এক পৃথিবী'},2:{en:'Living landscapes',bn:'জীবন্ত ভূদৃশ্য'},3:{en:'Five global clues',bn:'বিশ্বের পাঁচ সূত্র'},4:{en:'Listening to evidence',bn:'প্রমাণের কথা শোনা'},5:{en:'Your next question',bn:'তোমার পরের প্রশ্ন'}};
export const KIDS_STORY:[StoryScene,...StoryScene[]]=[
{id:'night',chapter:1,chapterTitle:C[1] as StoryText,artwork:'earth',sound:'space',title:{en:'A signal from Earth',bn:'পৃথিবীর এক সংকেত'},speaker:{en:'Tara',bn:'তারা'},dialogue:{en:'Rafi, look! Our planet has so many stories. Where should we begin?',bn:'রাফি, দেখো! আমাদের গ্রহের কত গল্প। কোথা থেকে শুরু করব?'},narration:{en:'Tara and Rafi meet Neel, a tiny satellite guide. Their journey crosses continents, but every measured claim must come from a NASA record.',bn:'তারা ও রাফির দেখা হলো নীল নামের ছোট স্যাটেলাইট গাইডের সঙ্গে। তারা মহাদেশ পেরিয়ে যাবে, কিন্তু প্রতিটি মাপা দাবি আসবে NASA রেকর্ড থেকে।'}},
{id:'guide',chapter:1,chapterTitle:C[1] as StoryText,artwork:'earth',sound:'signal',title:{en:'Questions have coordinates',bn:'প্রশ্নেরও স্থানাঙ্ক আছে'},speaker:{en:'Neel',bn:'নীল'},dialogue:{en:'Choose a city, a country reference point, or any coordinate. One point never speaks for an entire country.',bn:'শহর, দেশের নমুনা বিন্দু বা যেকোনো স্থানাঙ্ক বেছে নাও। একটি বিন্দু কখনো পুরো দেশের কথা বলে না।'},narration:{en:'Terra Earth keeps the place, years, variable and source together. A map marker is a sample location, not a national average.',bn:'টেরা আর্থ স্থান, বছর, সূচক ও উৎস একসঙ্গে রাখে। মানচিত্রের চিহ্ন একটি নমুনা স্থান, দেশের গড় নয়।'}},
{id:'delta',chapter:2,chapterTitle:C[2] as StoryText,artwork:'delta',sound:'river',title:{en:'Across living landscapes',bn:'জীবন্ত ভূদৃশ্য পেরিয়ে'},speaker:{en:'Rafi',bn:'রাফি'},dialogue:{en:'Rainforests, savannas, mountains and cities are connected through air, water and sunlight.',bn:'বন, সাভানা, পাহাড় আর শহর বায়ু, জল ও সূর্যালোকে যুক্ত।'},narration:{en:'Their illustrated journey moves from South America to Africa and Asia. The pictures help imagination; the evidence cards hold the observations.',bn:'ছবির যাত্রায় তারা দক্ষিণ আমেরিকা থেকে আফ্রিকা ও এশিয়ায় যায়। ছবি কল্পনায় সাহায্য করে; প্রমাণের কার্ডে থাকে পর্যবেক্ষণ।'}},
{id:'signals',chapter:2,chapterTitle:C[2] as StoryText,artwork:'signals',sound:'signal',title:{en:'Five windows on Earth',bn:'পৃথিবী দেখার পাঁচ জানালা'},speaker:{en:'Neel',bn:'নীল'},dialogue:{en:'Greenness, land temperature, air temperature, sunlight and rainfall each tell a different part of the story.',bn:'সবুজতা, ভূপৃষ্ঠের তাপ, বায়ুর তাপ, সূর্যালোক ও বৃষ্টি গল্পের আলাদা অংশ বলে।'},narration:{en:'Some locations have more complete records than others. Missing observations stay missing, even when we wish we knew the answer.',bn:'সব স্থানের রেকর্ড সমান সম্পূর্ণ নয়। উত্তর জানতে চাইলেও অনুপস্থিত পর্যবেক্ষণ অনুপস্থিতই থাকে।'}},
{id:'green',chapter:3,chapterTitle:C[3] as StoryText,artwork:'signals',sound:'forest',title:{en:'Brazil: the greenness clue',bn:'ব্রাজিল: সবুজের সূত্র'},speaker:{en:'Tara',bn:'তারা'},dialogue:{en:'NDVI compares plant greenness. It does not count every tree or photograph every leaf.',bn:'NDVI উদ্ভিদের সবুজতা তুলনা করে। এটি প্রতিটি গাছ গোনে না বা প্রতিটি পাতার ছবি তোলে না।'},narration:{en:'At a named Brazilian coordinate, they request MODIS vegetation records. They describe a direction only after enough years and a trend test are available.',bn:'ব্রাজিলের একটি নির্দিষ্ট স্থানাঙ্কে তারা MODIS উদ্ভিদ রেকর্ড চায়। যথেষ্ট বছর ও প্রবণতা পরীক্ষা থাকলেই তারা পরিবর্তনের দিক বলে।'},evidence:{districtId:'g_-3.1190_-60.0217_manaus',variable:'ndvi'}},
{id:'land',chapter:3,chapterTitle:C[3] as StoryText,artwork:'signals',sound:'city',title:{en:'Cairo: the ground is not the air',bn:'কায়রো: মাটি আর বাতাস এক নয়'},speaker:{en:'Rafi',bn:'রাফি'},dialogue:{en:'A warm rock and the air above it can have different temperatures. We need separate records.',bn:'উষ্ণ পাথর আর তার ওপরের বাতাসের তাপ আলাদা হতে পারে। আমাদের আলাদা রেকর্ড চাই।'},narration:{en:'MODIS observes land-surface temperature at their Cairo sample. The desert illustration is not a temperature measurement.',bn:'কায়রোর নমুনা স্থানে MODIS ভূপৃষ্ঠের তাপ পর্যবেক্ষণ করে। মরুভূমির ছবি তাপমাত্রার পরিমাপ নয়।'},evidence:{districtId:'g_30.0444_31.2357_cairo',variable:'lst'}},
{id:'air',chapter:3,chapterTitle:C[3] as StoryText,artwork:'signals',sound:'city',title:{en:'Tokyo: a record of the air',bn:'টোকিও: বাতাসের রেকর্ড'},speaker:{en:'Neel',bn:'নীল'},dialogue:{en:'NASA POWER provides air-temperature records. We test all the years, not just the hottest day.',bn:'NASA POWER বায়ুর তাপমাত্রার রেকর্ড দেয়। শুধু সবচেয়ে গরম দিন নয়, সব বছর পরীক্ষা করি।'},narration:{en:'Open the Tokyo evidence to read the measured values, their source and statistical strength. The story never invents a warming rate.',bn:'মাপা মান, উৎস ও পরিসংখ্যানের শক্তি জানতে টোকিওর প্রমাণ খোলো। গল্প কখনো উষ্ণতার হার বানায় না।'},evidence:{districtId:'g_35.6762_139.6503_tokyo',variable:'temperature'}},
{id:'sun',chapter:3,chapterTitle:C[3] as StoryText,artwork:'signals',sound:'dawn',title:{en:'Australia: following sunlight',bn:'অস্ট্রেলিয়া: সূর্যালোকের পথে'},speaker:{en:'Tara',bn:'তারা'},dialogue:{en:'Sunlight supports plants and solar panels. One cloudy year cannot tell us a long-term trend.',bn:'সূর্যালোক গাছ ও সোলার প্যানেলকে শক্তি দেয়। একটি মেঘলা বছর দীর্ঘমেয়াদি প্রবণতা বলে না।'},narration:{en:'At Sydney, they inspect annual solar-radiation records. Complete monthly observations are needed before a yearly value is accepted.',bn:'সিডনিতে তারা বার্ষিক সৌর বিকিরণ রেকর্ড দেখে। বার্ষিক মান নিতে সম্পূর্ণ মাসিক পর্যবেক্ষণ চাই।'},evidence:{districtId:'g_-33.8688_151.2093_sydney',variable:'solar'}},
{id:'rain',chapter:3,chapterTitle:C[3] as StoryText,artwork:'signals',sound:'rain',title:{en:'Nairobi: weather and climate',bn:'নাইরোবি: আবহাওয়া ও জলবায়ু'},speaker:{en:'Rafi',bn:'রাফি'},dialogue:{en:'Rain today is weather. A pattern over many years is what we test for climate.',bn:'আজকের বৃষ্টি আবহাওয়া। বহু বছরের ধরনই জলবায়ুর জন্য পরীক্ষা করি।'},narration:{en:'The Nairobi record keeps wet and dry years together. No single storm decides the trend, and no city sample represents all of Kenya.',bn:'নাইরোবির রেকর্ডে ভেজা ও শুকনো বছর একসঙ্গে থাকে। একটি ঝড় প্রবণতা ঠিক করে না, শহরের নমুনা পুরো কেনিয়ারও নয়।'},evidence:{districtId:'g_-1.2921_36.8219_nairobi',variable:'precipitation'}},
{id:'dots',chapter:4,chapterTitle:C[4] as StoryText,artwork:'evidence',sound:'signal',title:{en:'Two dots are not a trend',bn:'দুটি বিন্দু প্রবণতা নয়'},speaker:{en:'Neel',bn:'নীল'},dialogue:{en:'Every year between the first and last also matters.',bn:'প্রথম ও শেষের মাঝের প্রতিটি বছরও গুরুত্বপূর্ণ।'},narration:{en:'Their notebook gathers the full annual sequence. At least five annual values are required for the app’s trend analysis.',bn:'খাতায় জমা হয় সম্পূর্ণ বার্ষিক ধারাবাহিকতা। প্রবণতা বিশ্লেষণে অন্তত পাঁচটি বার্ষিক মান চাই।'}},
{id:'test',chapter:4,chapterTitle:C[4] as StoryText,artwork:'evidence',sound:'signal',title:{en:'How strong is the pattern?',bn:'ধরনটি কতটা শক্তিশালী?'},speaker:{en:'Tara',bn:'তারা'},dialogue:{en:'Mann–Kendall checks direction. A p-value helps us judge how clear the evidence is.',bn:'Mann–Kendall দিক যাচাই করে। p-value প্রমাণ কতটা স্পষ্ট তা বুঝতে সাহায্য করে।'},narration:{en:'When the test is not significant, they say no clear change in this window. That does not prove the planet is unchanging.',bn:'পরীক্ষা তাৎপর্যপূর্ণ না হলে তারা বলে এই সময়ে স্পষ্ট পরিবর্তন নেই। এতে গ্রহ অপরিবর্তিত প্রমাণ হয় না।'}},
{id:'rate',chapter:4,chapterTitle:C[4] as StoryText,artwork:'evidence',sound:'signal',title:{en:'The pace of change',bn:'পরিবর্তনের গতি'},speaker:{en:'Rafi',bn:'রাফি'},dialogue:{en:'Theil–Sen estimates the rate while resisting unusual years. The units and time window matter.',bn:'Theil–Sen অস্বাভাবিক বছরের টান সামলে হার হিসাব করে। একক ও সময়সীমা গুরুত্বপূর্ণ।'},narration:{en:'A computer calculates the slope from observations. AI can explain the result, but cannot invent or replace it.',bn:'পর্যবেক্ষণ থেকে কম্পিউটার ঢাল হিসাব করে। AI ফল বোঝাতে পারে, বানাতে বা বদলাতে পারে না।'}},
{id:'journal',chapter:5,chapterTitle:C[5] as StoryText,artwork:'evidence',sound:'dawn',title:{en:'A journal anyone can check',bn:'যে খাতা সবাই যাচাই করতে পারে'},speaker:{en:'Neel',bn:'নীল'},dialogue:{en:'Keep the coordinate, source, retrieval date and years beside every claim.',bn:'প্রতিটি দাবির পাশে স্থানাঙ্ক, উৎস, সংগ্রহের তারিখ ও বছর রাখো।'},narration:{en:'Across Europe and every other continent, honest comparisons use matching periods and distinguish point samples from regional averages.',bn:'ইউরোপ ও সব মহাদেশে সৎ তুলনায় একই সময় নেওয়া হয়, বিন্দুর নমুনা ও এলাকার গড় আলাদা রাখা হয়।'}},
{id:'challenge',chapter:5,chapterTitle:C[5] as StoryText,artwork:'future',sound:'dawn',title:{en:'Your next place on Earth',bn:'পৃথিবীতে তোমার পরের স্থান'},speaker:{en:'Tara and Rafi',bn:'তারা ও রাফি'},dialogue:{en:'Choose a place you care about. Ask a question, check the record, and tell only what the evidence supports.',bn:'তোমার প্রিয় স্থান বেছে নাও। প্রশ্ন করো, রেকর্ড দেখো, প্রমাণ যতটুকু বলে ততটুকুই বলো।'},narration:{en:'The journey ends with a calm review, but your investigation can begin anywhere on Earth.',bn:'শান্ত পর্যালোচনায় যাত্রা শেষ, কিন্তু তোমার অনুসন্ধান পৃথিবীর যেকোনো স্থানে শুরু হতে পারে।'}},
];
