import { useEffect, useMemo, useRef, useState } from 'react';
import Globe, {type GlobeMethods} from 'react-globe.gl';
import { districts, getSeries, type VariableKey } from '@/lib/climate';
import { coordinateLocation, coordinatesLabel } from '@/lib/global-locations';
import { registerEvidence, getCached } from '@/lib/climate';
import { useLang } from '@/lib/i18n';
import { normalize, spectralColor } from '@/lib/colors';
import { Button } from './ui/button';
export interface GlobeExplorerProps {
 variable:VariableKey;phase:'world'|'bangladesh';onPhaseChange:(phase:'world'|'bangladesh')=>void;onSelectDistrict:(id:string)=>void;
 hexMode?:boolean;gridPoints?:{lat:number;lng:number;value:number;sig?:boolean}[];gridUnit?:string;gridCaption?:string;
 regionalMode?:boolean;selectedRegionalId?:string;onSelectRegional?:(id:string)=>void;
}
export default function GlobeExplorer({variable,onSelectDistrict,hexMode=false,gridPoints=[],gridUnit='',gridCaption='',regionalMode=false,onSelectRegional}:GlobeExplorerProps){
 const ref=useRef<GlobeMethods|undefined>(undefined);const wrap=useRef<HTMLDivElement>(null);const {lang}=useLang();
 const [size,setSize]=useState({w:320,h:420});const [spin,setSpin]=useState(false);const [names,setNames]=useState(false);
 useEffect(()=>{const el=wrap.current;if(!el)return;const ro=new ResizeObserver(()=>setSize({w:Math.floor(el.clientWidth),h:Math.floor(el.clientHeight)}));ro.observe(el);setSize({w:el.clientWidth,h:el.clientHeight});return()=>ro.disconnect();},[]);
 const points=useMemo(()=>districts.filter(x=>x.id.startsWith('g_')||['bangladesh','india','pakistan','nepal','bhutan','sri-lanka','afghanistan','maldives','myanmar'].includes(x.id)).map(x=>({id:x.id,lat:x.lat,lng:x.lon,name:lang==='bn'?x.bn:x.name,value:getSeries(x.id,variable).at(-1)?.value})),[variable,lang]);
 const bounds=useMemo(()=>{const values=gridPoints.map(x=>x.value);return values.length?{min:Math.min(...values),max:Math.max(...values)}:{min:0,max:1};},[gridPoints]);
 useEffect(()=>{const g=ref.current;if(!g)return;const controls=g.controls() as {autoRotate:boolean;autoRotateSpeed:number};controls.autoRotate=spin&&!matchMedia('(prefers-reduced-motion: reduce)').matches;controls.autoRotateSpeed=0.4;},[spin,size]);
 function select(lat:number,lon:number){const location=coordinateLocation(lat,lon);registerEvidence(location,getCached(location.id)??{district:location.id,variables:{}});onSelectDistrict(location.id);}
 const tooltip=(p:{name?:string;lat:number;lng:number;value?:number | undefined})=>`<div class="globe-tooltip"><strong>${p.name??coordinatesLabel(p.lat,p.lng)}</strong><br/>${p.value===undefined?(lang==='bn'?'NASA তথ্য খুলুন':'Open NASA evidence'):`${p.value.toFixed(2)} ${gridUnit}`}<br/>${gridCaption}</div>`;
 return <div ref={wrap} className="relative h-full w-full"><Globe ref={ref} width={size.w} height={size.h} backgroundColor="rgba(0,0,0,0)" globeImageUrl="/textures/earth-blue-marble.jpg" bumpImageUrl="/textures/earth-topology.png" showAtmosphere atmosphereAltitude={0.15} onGlobeReady={()=>ref.current?.pointOfView({lat:15,lng:10,altitude:2.4})} onGlobeClick={({lat,lng})=>select(lat,lng)} pointsData={hexMode?[]:points} pointLat="lat" pointLng="lng" pointAltitude={0.006} pointRadius={0.35} pointColor={()=>getComputedStyle(document.documentElement).getPropertyValue('--color-primary').trim() || 'rgb(124, 111, 240)'} pointLabel={p=>tooltip(p as typeof points[number])} onPointClick={p=>{const id=(p as typeof points[number]).id;regionalMode?onSelectRegional?.(id):onSelectDistrict(id);}} labelsData={names&&!hexMode?points:[]} labelLat="lat" labelLng="lng" labelText="name" labelSize={0.8} labelDotRadius={0.2} labelColor={()=>getComputedStyle(document.documentElement).getPropertyValue('--color-foreground').trim() || 'rgb(238,246,248)'} onLabelClick={p=>onSelectDistrict((p as typeof points[number]).id)} hexBinPointsData={hexMode?gridPoints:[]} hexBinPointLat="lat" hexBinPointLng="lng" hexBinPointWeight="value" hexBinResolution={4} hexMargin={0.15} hexTopColor={b=>{const x=b as {sumWeight:number;points:unknown[]};return spectralColor(variable,normalize(x.sumWeight/Math.max(1,x.points.length),bounds.min,bounds.max),0.95);}} hexSideColor={b=>{const x=b as {sumWeight:number;points:unknown[]};return spectralColor(variable,normalize(x.sumWeight/Math.max(1,x.points.length),bounds.min,bounds.max),0.5);}} hexAltitude={b=>{const x=b as {sumWeight:number;points:unknown[]};return 0.02+0.15*normalize(x.sumWeight/Math.max(1,x.points.length),bounds.min,bounds.max);}} hexLabel={b=>{const x=b as {sumWeight:number;points:{lat:number;lng:number;sig?:boolean}[]};const p=x.points[0];return p?tooltip({...p,value:x.sumWeight/Math.max(1,x.points.length)}):'';}} onHexClick={b=>{const p=(b as {points:{lat:number;lng:number}[]}).points[0];if(p)select(p.lat,p.lng);}}/><div className="absolute bottom-3 left-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" className="bg-card/90" onClick={()=>ref.current?.pointOfView({lat:15,lng:10,altitude:2.4},600)}>{lang==='bn'?'পুরো পৃথিবী':'Whole Earth'}</Button><Button size="sm" variant={spin?'default':'outline'} aria-pressed={spin} className="bg-card/90" onClick={()=>setSpin(x=>!x)}>{lang==='bn'?'ঘোরান':'Rotate'}</Button>{!hexMode?<Button size="sm" variant="outline" aria-pressed={names} className="bg-card/90" onClick={()=>setNames(x=>!x)}>{lang==='bn'?'স্থানের নাম':'Place names'}</Button>:null}</div></div>;
}
