import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { LocationSearch } from './LocationSearch';
import { Button } from './ui/button';
import { analyzeVariable, getDistrict, VARIABLE_KEYS, VARIABLE_LABEL_KEY } from '@/lib/climate';
import { useLocationEvidence } from '@/lib/location-evidence';
import { useLang,fmt } from '@/lib/i18n';
import { ProvenanceButton } from './ProvenanceDrawer';
export interface RegionalSelection {active:boolean;variable:typeof VARIABLE_KEYS[number];selectedId:string;onSelect:(id:string)=>void;onVariable:(variable:typeof VARIABLE_KEYS[number])=>void;onActive:(active:boolean)=>void}
export function SouthAsiaComparison({selection}:{selection:RegionalSelection}) {
 const {lang,t}=useLang();const [baseline,setBaseline]=useState('india');
 const a=useLocationEvidence(selection.selectedId,selection.variable==='ndvi'||selection.variable==='lst');
 const b=useLocationEvidence(baseline,selection.variable==='ndvi'||selection.variable==='lst');
 const first=selection.selectedId.startsWith("g_")&&!a.hydrated?null:analyzeVariable(selection.selectedId,selection.variable),second=baseline.startsWith("g_")&&!b.hydrated?null:analyzeVariable(baseline,selection.variable);
 return <section className="border-y border-border bg-elevated/55"><div className="mx-auto max-w-7xl px-3 py-6 sm:px-6"><h2 className="font-display text-3xl">{lang==='bn'?'পৃথিবীজুড়ে তুলনা':'Compare across Earth'}</h2><p className="mt-2 text-xs text-muted-foreground">{lang==='bn'?'নির্দিষ্ট স্থানাঙ্কের নমুনা; দেশের গড় নয়।':'Named coordinate samples, never country averages.'}</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><LocationSearch label={lang==='bn'?'প্রথম স্থান':'First location'} onSelect={selection.onSelect}/><LocationSearch label={lang==='bn'?'দ্বিতীয় স্থান':'Second location'} onSelect={setBaseline}/></div><div className="my-4 flex flex-wrap gap-2">{VARIABLE_KEYS.map(v=><Button key={v} size="sm" variant={v===selection.variable?'default':'outline'} onClick={()=>selection.onVariable(v)}>{t(VARIABLE_LABEL_KEY[v])}</Button>)}</div>{a.isFetching||b.isFetching?<p role="status" className="text-accent">{lang==='bn'?'NASA রেকর্ড আসছে…':'Loading NASA records…'}</p>:null}<div className="grid gap-4 sm:grid-cols-2">{[{id:selection.selectedId,analysis:first},{id:baseline,analysis:second}].map(x=><article key={x.id} className="border-l-2 border-primary pl-4"><h3 className="font-display text-xl">{getDistrict(x.id)?.name??x.id}</h3>{x.analysis?<><p className="mt-2">{fmt(x.analysis.result.current_value??0,lang,2)} {x.analysis.unit}</p><p className="mt-1 text-xs text-muted-foreground">{x.analysis.result.period.start}–{x.analysis.result.period.end} · p = {fmt(x.analysis.result.trend.p_value,lang,3)} · {fmt(x.analysis.result.slope.slope_per_decade,lang,3)} / {lang==='bn'?'দশক':'decade'}</p><ProvenanceButton provenance={x.analysis.provenance} title={getDistrict(x.id)?.name??x.id} payload={x.analysis}/></>:<p className="mt-2 text-sm text-muted-foreground">{lang==='bn'?'এই সূচকের যথেষ্ট তথ্য নেই।':'Not enough records for this variable.'}</p>}</article>)}</div><Button asChild variant="outline" className="mt-5"><Link to="/compare" search={{districtA:selection.selectedId,districtB:baseline}}>{lang==='bn'?'পূর্ণ তুলনা খুলুন':'Open full comparison'}</Link></Button></div></section>;
}
